### ISSUE TITLE
Update Project READ Me , describe technologies used

### ISSUE THREAD

**Issue by rajilsaj** [rajilsaj/udaudo-nepal-template#1]
Update Project READ Me , describe technologies used

**Comment by Anuja5** [comment]
[RequirementSpecificationUdaudoNepal.pdf](https://github.com/rajilsaj/udaudo-nepal-template/files/3357588/RequirementSpecificationUdaudoNepal.pdf)

**Comment by Anuja5** [comment]
Project Plan Overview and Requirement Analysis
[RequirementSpecificationUdaudoNepal.pdf](https://github.com/rajilsaj/udaudo-nepal-template/files/3357590/RequirementSpecificationUdaudoNepal.pdf)
